# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.CRAD <- function(X, X_lin, knots, knotsidx, NS, bdmargin) {
    .Call('_gambms_CRAD_cpp', PACKAGE = 'gambms', X, X_lin, knots, knotsidx, NS, bdmargin)
}

.CRAD_test <- function(testX, X_lin, CRADlist) {
    .Call('_gambms_CRAD_test_cpp', PACKAGE = 'gambms', testX, X_lin, CRADlist)
}

.gambmsEVEN <- function(y, glmWeight, X, X_pr, XLin, offset, maxk, Lambda, familyLink, gprior, aa, bb, ss, gg, enumerate, numMCcandidate, MCiter, MCMCiter, Rglm, nearPDres, storeFit, printiter) {
    .Call('_gambms_gambmsEVEN', PACKAGE = 'gambms', y, glmWeight, X, X_pr, XLin, offset, maxk, Lambda, familyLink, gprior, aa, bb, ss, gg, enumerate, numMCcandidate, MCiter, MCMCiter, Rglm, nearPDres, storeFit, printiter)
}

.gambmsFREE <- function(y, glmWeight, X, X_pr, XLin, offset, maxk, Lambda, familyLink, gprior, aa, bb, ss, gg, initS, MCMCiter, thin, bir_p, dea_p, nu, Rglm, nearPDres, storeFit, printiter) {
    .Call('_gambms_gambmsFREE', PACKAGE = 'gambms', y, glmWeight, X, X_pr, XLin, offset, maxk, Lambda, familyLink, gprior, aa, bb, ss, gg, initS, MCMCiter, thin, bir_p, dea_p, nu, Rglm, nearPDres, storeFit, printiter)
}

.gambmsVS <- function(y, glmWeight, X, X_pr, XLin, offset, maxk, Lambda, familyLink, gprior, aa, bb, ss, gg, MCMCiter, Rglm, nearPDres, getmeMAP, storeFit, printiter) {
    .Call('_gambms_gambmsVS', PACKAGE = 'gambms', y, glmWeight, X, X_pr, XLin, offset, maxk, Lambda, familyLink, gprior, aa, bb, ss, gg, MCMCiter, Rglm, nearPDres, getmeMAP, storeFit, printiter)
}

.rCH <- function(nsamp, burnin, aa, bb, ss) {
    .Call('_gambms_rCH_cpp', PACKAGE = 'gambms', nsamp, burnin, aa, bb, ss)
}

.rGH <- function(nsamp, burnin, aa, bb, xx, zz) {
    .Call('_gambms_rGH_cpp', PACKAGE = 'gambms', nsamp, burnin, aa, bb, xx, zz)
}

.rtCCH <- function(nsamp, burnin, aa, bb, zz, ss, nu, theta) {
    .Call('_gambms_rtCCH_cpp', PACKAGE = 'gambms', nsamp, burnin, aa, bb, zz, ss, nu, theta)
}

.rAH <- function(nsamp, burnin, aa, bb, zz, ww, xx, yy) {
    .Call('_gambms_rAPL_cpp', PACKAGE = 'gambms', nsamp, burnin, aa, bb, zz, ww, xx, yy)
}

